services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_DIALECT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PWD: example
      DB_NAME: minha_base
      NODE_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: minha_base
    volumes:
      - ./data:/var/lib/mysql
